# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79fe3089965c544bee71d61a31358e496d1cc437f7774f023a10c5fbe261539722e5c1b88f82874ba45a2e3c4784098feb927b1ee93479532cd695c73149c34b

test:
  secret_key_base: 9ab19301efcf8f4a6d26eef10782d4c7caceb9daae86f7fcbf39fe64dea3c4d4462d234dfca4abddb1fefbfc8cca3f06d789146eea3706527ade84592c102840

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
